import { normalizeWorldbuildingName } from './worldbuilding';
import type { WorldbuildingEntry, WorldbuildingKind } from '../types';

/**
 * Deliberately hand-curated from the user's `Tales on Unwritten Tomes` source.
 * This is not a heading or prose-name extractor: every record and classification
 * below was chosen individually so the campaign starts with a useful reference set.
 */
export type CuratedReference = {
  name: string;
  kind: WorldbuildingKind;
  aliases?: string[];
  notes: string;
};

const reference = (name: string, kind: WorldbuildingKind, notes: string, aliases?: string[]): CuratedReference => ({ name, kind, notes, aliases });

export const talesOnUnwrittenTomesReferences: readonly CuratedReference[] = [
  // World, realms, and powers
  reference('Belentor', 'region', 'The campaign continent and primary setting.'),
  reference('The Celestial Handful', 'region', 'The world travelling the cosmic rivers, guided by the stars.'),
  reference('Erylmar', 'deity', 'Prime creator of the world. Her departure defines the setting’s absent afterlife.', ['Erylmar the Creator']),
  // The Celestial Handful pantheon
  reference('Eldorin', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Eryab', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Fugrar', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Silvin', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Avoldin', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Wheina', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Auren', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Shungdro', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Gargadjinn', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Myar', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Zylar', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Elyndra', 'deity', 'Greater deity of the Celestial Handful pantheon.'),
  reference('Vorrak', 'deity', 'Greater deity of the Celestial Handful pantheon.', ['Varrak']),
  reference('Hin Ge', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Iroth', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Ellehirn', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Brirvock', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Korbyglum', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Aiv', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Onro', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Vraxis', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Fabrian', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Silien', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Chuny', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference('Lowi', 'deity', 'Lesser deity of the Celestial Handful pantheon.'),
  reference("Enc'thrii", 'landmark', 'The ice moon whose alignment with Din and Unri forms the autumn Perigee.'),
  reference('Monarchy of Sharlai', 'faction', 'One of the four warring monarchies. The party is commissioned under its authority.', ['Sharlai', 'Royal Crown']),
  reference('Monarchy of Zsweon', 'faction', 'A rival monarchy pressuring Sharlai’s eastern border.', ['Zsweon']),
  reference('Monarchy of Illoni', 'faction', 'Underground monarchy whose cities and factories occupy deep crevasses; it is creating Nothics to seek Canein’s crypt.', ['Illoni']),
  reference('Levenvey', 'region', 'A monarchy bordering the Tickwood area alongside Zsweon and Illoni.'),
  reference('Doulm', 'region', 'Desert-border nation with a strict social hierarchy of magic and rules governing its use.'),
  reference('Noag Desert', 'region', 'Desert landscape beyond Fenegral’s Ridge, shaped during a First Generation battle.'),
  reference("The Lute's Head", 'region', 'The road region north of Gyrro and Addersilk, where bandits and wandering threats are common.'),
  reference('Bandit Lands', 'region', 'Lawless territory between the Floating Moat and Addersilk.'),
  reference('Tickwood Forest', 'region', 'Forest near the Zsweon, Levenvey, and Illoni borders; rumoured vicinity of Canein’s Contingency.'),
  reference("Erylmar's Throne", 'landmark', 'Vacant throne carved from a mountain above a contained abyssal breach.'),
  reference('Kingcrypt', 'landmark', 'A tunnel-maze of royal crypts and lingering curses, entered by a passwall route.'),
  reference('Rocklund', 'town', 'Setting of the Deathduggers’ descent into Kingcrypt.'),
  reference('City of the Banished', 'town', 'City between Boarguild and the Isle of Thieves where Isabelle Outcast works on Space Gainers.'),
  reference('Boarguild', 'town', 'Settlement named as lying near the City of the Banished.'),
  reference('Isle of Thieves', 'landmark', 'Island named as lying near the City of the Banished.'),
  reference('Kelemvorium', 'town', 'Place in Starseek where Algeeir Fiddlewink observes the Dive Star.'),
  reference('Starseek', 'town', 'City containing Kelemvorium.'),
  reference('Canein Ilvur', 'historical-figure', 'Legendary wizard whose hidden works, including the Contingency, drive the campaign.'),
  reference('The Contingency', 'item', 'Canein Ilvur’s constructed post-death device, protected by monsters and magical traps.'),
  reference('Space Gainers', 'item', 'Small stone spheres receiving staged geometric enchantments; Isabelle Outcast is completing their second of five enchantments.'),
  reference('Soul Box', 'item', 'A crafted vessel for a soul; frequent burial, magical, and criminally exploited object in the campaign.', ['Soul Boxes']),
  reference('Soulinterim', 'item', 'A three-part device that converts a captured soul into charges for necromantic magic.'),
  reference('Oblivion Lens', 'item', 'Ancient arcane focus in Gyrro’s lower catacombs, currently being retrofitted by kobolds.', ['Transmuter Focus']),

  // First chapter and the Gyrro route
  reference('Chant', 'town', 'Sharlaian city from which the party receives its initial direction and road connections.'),
  reference('Eastlyre and Hook Inn', 'landmark', 'Functional inn and staging point where the party meets before its first mission.', ['Eastlyre & Hook']),
  reference('Chantador Crowfee Indissian', 'character', 'Seasoned Sharlaian officer and the party’s reporting contact around Chant.', ['Chantador Indissian']),
  reference('Rowan "Fiddle" Duskwind', 'character', 'Proprietor of the Eastlyre and Hook Inn.', ['Rowan Duskwind', 'Fiddle Duskwind']),
  reference('Meat Madness', 'creature', 'The party’s ox; its name is only knowable through speak with animals.'),
  reference('White Scarves', 'organization', 'A recognisable marker said to discourage some bandits and opportunistic mercenaries.'),
  reference('Thomas Creed Outpost', 'landmark', 'Border resupply and check-in post before Doulm.', ['Doulm Bordercrossing Post']),
  reference('Thomas Creed', 'character', 'Field Officer and Measurekeeper at the Doulm border outpost.', ['Measurekeeper Creed']),
  reference('Ridge of Fendral', 'landmark', 'Route encounter location north of Gyrro.', ['Ridge of Fenegral', "Fenegral's Ridge"]),
  reference('Nomadic Ungo Keepers', 'organization', 'Farmers who raise and follow migratory Ungo for meat and feathers.'),
  reference('Chin Riverbreak', 'character', 'Ungo Keeper taken by goblins during the route encounter.'),
  reference('Ibbi Riverbreak', 'character', 'Ungo Keeper and mother in the Riverbreak family.'),
  reference('Yngliad Riverbreak', 'character', 'Ungo Keeper and father in the Riverbreak family.'),
  reference('Karr Riverbreak', 'character', 'Child of the Riverbreak family.'),
  reference('Skrag', 'character', 'Goblin involved in the Cackle Fever road encounter.'),
  reference('Frikna', 'character', 'Goblin involved in the Cackle Fever road encounter.'),
  reference('Thwip', 'character', 'Goblin involved in the Cackle Fever road encounter.'),
  reference('Goblin Experiments', 'landmark', 'Cave occupied by goblins exploiting an ancient arcane channeling construct.'),
  reference('Cvenwove', 'character', 'Locathah hunter trapped in the Goblin Experiments well and allied with its goblins.'),
  reference('The Artifact', 'item', 'Ancient stone-and-metal arcane channeling construct in the goblin cave; it once opened a watery planar portal.'),
  reference('The Floating Moat', 'landmark', 'An upside-down floating inn over a crevasse; its mass must be periodically carved back.', ['Bridgeinn']),
  reference('Fedlic Wove', 'character', 'Perpetually stressed proprietor of the Floating Moat.'),
  reference('Scented Safety', 'faction', 'Protection-racket band operating from an abandoned military site near the Floating Moat.'),
  reference('Cleat Gobsslay', 'character', 'Pragmatic leader of Scented Safety, exploiting the lack of protection south of the Lute’s Head.'),
  reference('Brennet Hail', 'character', 'Cleat Gobsslay’s second-in-command, responsible for Scented Safety’s daily operations.'),
  reference('Dully Barleythrasher', 'character', 'Leader of a Scented Safety team operating from an old toll house.', ['Dully']),
  reference('Brave Peter', 'character', 'Scented Safety team leader who poses as a Chant town guard.', ['Peter']),
  reference('Fennick Lowheel', 'character', 'Illonite Scented Safety member with seizures tied to a mysterious gift.'),
  reference('Legless', 'creature', 'Creature kept in a covered cage by Scented Safety; made by Fennick.'),

  // Gyrro and catacombs
  reference('Gyrro', 'town', 'Mushroom-farming town at the south border of the Lute’s Head, known for Din divination and psychedelic festivals.'),
  reference('Gyrro Catacombs', 'landmark', 'Multi-level burial complex beneath Gyrro, containing royal claims, cranium-rat activity, kobolds, and the Oblivion Lens.', ['Catacombs of Gyrro']),
  reference('Spiral Market', 'landmark', 'Gyrro’s spiralling farmers’ and wares market.'),
  reference('Resident Throng', 'landmark', 'Winding residential district leading to Gyrro Town Hall.'),
  reference('Gardens of Sigh', 'landmark', 'Six gardens around a blocked spiral descent into Gyrro’s undercity.', ['Garden of Sighs']),
  reference('Cradeling Amphitheatre', 'landmark', 'Sunken Gyrro venue for music, illusion, and festival speeches.'),
  reference('Bettred Nuum', 'historical-figure', 'Famed diviner blamed for manifesting a fatal sickness by speaking a prophecy of death; the illness is called Nuum.'),
  reference('Derrin Cade', 'character', 'Cheerful but capable Gyrro guard who mediates disputes and hosts festival proceedings.'),
  reference('Taryn Flint', 'character', 'Rule-focused Gyrro guard wary of outsiders.', ['Tharyn Flint']),
  reference('Edwin Galmere', 'character', 'Mayor of Gyrro and speaker of the Din darkening prophecy.', ['Edwin Galmore']),
  reference('Faron Whitlock', 'character', 'Young, organised aide to Mayor Galmere.'),
  reference('Harrid Stonehelm', 'character', 'Mute Gyrro blacksmith whose tools and weapons are prized for durability.'),
  reference('Ansel Redwick', 'character', 'Shrewd Gyrro general-store owner and haggler.'),
  reference('Captain Serel Aimon', 'character', 'Gyrro Nightwatch Captain investigating attacks on the town’s food stores.'),
  reference('Delwin Orse', 'character', 'Gyrro Spoorkeeper who protects and monitors the spore blooms sustaining its mushroom trade.'),
  reference('Corven Holt', 'character', 'Gyrro market vendor feuding with neighbouring families.'),
  reference('Clover Holt', 'character', 'Corven Holt’s wife and participant in the Spiral Market feud.'),
  reference('Kalen Cartwright', 'character', 'Member of the Cartwright family in the Spiral Market feud.'),
  reference('Sylra Cartwright', 'character', 'Member of the Cartwright family in the Spiral Market feud.'),
  reference('Sarah Lowfield', 'character', 'Member of the Lowfield family in the Spiral Market feud.'),
  reference('Trung Lowfield', 'character', 'Member of the Lowfield family in the Spiral Market feud.'),
  reference('Chiff Lowfield', 'character', 'Child of Sarah and Trung Lowfield.'),
  reference('Osrik Tanner', 'character', 'Local human paladin in Gyrro.'),
  reference('Princess Caelinia', 'character', 'Royal patron seeking a discreet correction of the Gyrro catacomb burial records.'),
  reference('House Abune', 'organization', 'Noble family ordered to be recorded as occupants of Gyrro’s inaccurately named royal crypts.'),
  reference('House of Chant', 'organization', 'Esteemed noble family given custodianship of the disputed Gyrro vaults.'),
  reference('High Priestess Mereth Darlowe', 'character', 'Physician and catacomb patron seeking an escort.'),
  reference('Master Builder Torvek Ironveil', 'character', 'Catacomb patron connected to collapsed halls and quarry shafts.'),
  reference('Archivist Selbreen Quillhand', 'character', 'Human scholar and catacomb patron connected to the record chambers.'),
  reference('House Valmor', 'organization', 'Merchant kin with a family crypt in Gyrro’s catacombs.'),
  reference('Lady Elira Valmor', 'character', 'Member of House Valmor connected to the Gyrro family crypts.'),
  reference('House Tharrek', 'organization', 'Merchant kin with a family crypt in Gyrro’s catacombs.'),
  reference('Orenn Tharrek', 'character', 'Member of House Tharrek connected to the Gyrro family crypts.'),
  reference('House Deylin', 'organization', 'Merchant kin with a family crypt in Gyrro’s catacombs.'),
  reference('Maelis Deylin', 'character', 'Member of House Deylin connected to the Gyrro family crypts.'),
  reference('Old Fendrick Hale', 'character', 'Elder representing the common denizens of Gyrro.'),
  reference('Haundry', 'character', 'Unstable catacomb guardian obsessed with giving rats collective intelligence.', ['Handry', 'Haundy', 'Haundey']),
  reference('King Cranium', 'creature', 'Giant cranium rat who communicates with Haundry and directs a rat archive.', ['KC']),
  reference('Bleeding Wing', 'character', 'Unnamed ghost in the Restless Crypt, seeking the return of its stolen soul box.'),
  reference('House Vaylyth', 'organization', 'Surname carved on the empty royal crypts in Gyrro.'),
  reference('Aerin Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Selindra Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Malric Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Elayne Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Tharion Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Kaelen Vaylyth', 'historical-figure', 'Named occupant of a Gyrro royal crypt.'),
  reference('Maerra Vaylyth', 'historical-figure', 'Child named as an occupant of a Gyrro royal crypt.'),
  reference('Faysol Vaylyth', 'historical-figure', 'Young adult named as an occupant of a Gyrro royal crypt.'),
  reference('Shone Inkwell', 'historical-figure', 'Eryab priest commemorated by a quarry-era statue in the lower catacombs.'),

  // Roads, Addersilk, and the merrow arc
  reference('Addersilk', 'town', 'Lake-side silk town flooded on a three-day cycle, built around the Craunt Adder silk harvest.'),
  reference('Adderlake', 'landmark', 'Underground-fed lake whose cycle floods Addersilk and renews the Craunt Adders’ silk spawning grounds.'),
  reference('Craunt Adder', 'creature', 'Amphibious creature farmed in Addersilk for the silk produced at its spawning grounds.'),
  reference('Silkmaster Tone Calegg', 'character', 'Druid who oversees Addersilk’s silk harvest and hires help against the Sublake Merrow.', ['Tone Calegg']),
  reference('Sootman', 'character', 'Addersilk blacksmith.'),
  reference('Archibald Raught', 'character', 'Respected Addersilk elder, former traveller, and student of tides and stars.'),
  reference('Thrini Raught', 'character', 'Archibald Raught’s late wife; her urn is to be decorated with clam pearls.'),
  reference('Habiniah Drove', 'character', 'Seventeen-year-old Addersilk resident planning to leave with her boyfriend Gash.'),
  reference('Gash', 'character', 'Habiniah Drove’s boyfriend and a medical assistant in Addersilk.'),
  reference('Meryn Driftbale', 'character', 'Addersilk resident grieving her late husband and daughter, now repeatedly imprisoned for drunken disorder.'),
  reference('Yulven Driftbale', 'character', 'Meryn Driftbale’s late husband.'),
  reference('Neyleen Driftbale', 'character', 'Meryn Driftbale’s late daughter.'),
  reference('Singer Crow', 'character', 'Leader of a merchant band travelling north from Illoni through Doulm.'),
  reference('Tavren Surnholt', 'character', 'Merchant dealing in gemstones, pearls, crystals, powders, and spell components.'),
  reference('Arn Sales', 'character', 'Travelling philosopher and theologian studying regional views on Erylmar’s abandonment and the stars.'),
  reference('Dravik Mounsel', 'character', 'Merchant travelling toward Kingcrypts while collecting potion ingredients.'),
  reference('Mirre Shalken', 'character', 'Merchant travelling to escape the warring efforts and selling prosthetic limbs.'),
  reference('Fiddles Fuck', 'landmark', 'Addersilk tavern and music venue run by Hornhound.'),
  reference('Hornhound', 'character', 'Proprietor of Fiddles Fuck, serving local brews in brass instrument bells.'),
  reference('Alabaster Stairs', 'landmark', 'High-end Addersilk tavern with imported Doulmian food and wines.'),
  reference('Lady Wiles', 'character', 'Bejewelled owner of the Alabaster Stairs, rumoured to have Djinni blood.'),
  reference('Lawless Incan', 'landmark', 'Makeshift Addersilk drinking establishment run under a boat sail.'),
  reference('Jingo Split', 'character', 'Half-orc who runs the Lawless Incan but is forbidden to own land or an establishment.'),
  reference('Merrow Queen', 'character', 'Ruler of the submerged merrow settlement and wielder of Quadrent Drudge.', ['Queen of the Quadrent']),
  reference('Quadrent Drudge', 'item', 'Rare merrow queen weapon with returnable poison, paralysis, and barbed spikes.'),
  reference('Thronereef', 'landmark', 'Massive submerged coral throne complex where the Merrow Queen resides.'),
  reference('Merrowwatch', 'landmark', 'Grown coral watchtower used to spot pyre signals and approaching threats.'),
  reference('Merrowfort', 'landmark', 'Main defensive position of the merrow, formed by reef clusters, guards, warning horn, and signal pyres.'),
  reference('Blighted Reef', 'landmark', 'Diseased reef where merrow outcasts and those with mutations live.'),
  reference('Merrowspawn', 'landmark', 'Area where adolescent merrow are kept and schooled.'),
  reference('Spawning Shallows', 'landmark', 'Temperature-stable area where merrow eggs are maintained.'),
  reference('The Highborn Liberation Front', 'faction', 'Bandit group employing a necromancer to prepare for Unri, using road-jacking, kidnapping, and ransoms.'),
  reference('Rajine Ospray', 'character', 'Leader associated with the Highborn Liberation Front.'),
  reference('F Chord', 'faction', 'Smuggler band operating in the Bandit Lands.'),
  reference('Akka Glosser', 'character', 'Leader associated with F Chord.'),
  reference('The Tusk-Twins', 'faction', 'Orc slavers and raiders operating in the Bandit Lands.'),
  reference('Darkscithe Dining', 'landmark', 'Inn or tavern in the Bandit Lands.'),

  // Doulm border, quarry, and intelligence plot
  reference('Fenegral', 'historical-figure', 'First Generation figure whose creation stone stripped the land that became the Noag Desert.'),
  reference('House Cact', 'organization', 'House associated with the necromancer apprentice Zelough.'),
  reference('Zelough of the Cact House', 'character', 'Necromancer’s apprentice, infiltrator of the Sky-Guard, and grieving parent seeking power.'),
  reference('Heir Thou', 'character', 'Heir to House Cact.'),
  reference('Carastring', 'town', 'Zelough’s home town, where undead killed and raised much of the population.'),
  reference('Lanch Fiboar', 'character', 'Wizard’s apprentice managing the royal limestone quarry charter near Doulm.'),
  reference('Dignity Crew', 'organization', 'One of four quarry work crews.'),
  reference('Honour Crew', 'organization', 'One of four quarry work crews.'),
  reference('Equitious Crew', 'organization', 'One of four quarry work crews.'),
  reference('God-fearing Crew', 'organization', 'One of four quarry work crews.'),
  reference('Kharrek Intis', 'character', 'Superstitious quarry crew leader raised in violent slavery.'),
  reference('Sileon Crest', 'character', 'Quarry crew leader.'),
  reference('Bastor Condoe', 'character', 'Gambling-addicted quarry crew leader indebted to the Sky-Guard.'),
  reference('Ravik Qullastair', 'character', 'Quarry crew leader whose Doulmian citizenship was revoked for anti-corruption radicalism.'),
  reference('Altadune Dredger', 'character', 'Sharlaian cleric assigned to protect and heal quarry workers.', ['Ælt']),
  reference('Gjhiddiji Gchu', 'character', 'Sharlaian cleric assigned to protect and heal quarry workers.'),
  reference('Lady Sharf Vindietu', 'character', 'Captain leading a 200-soldier mercenary body-collection contract.', ['Lady Sharf', 'Lady Sarf Vindietu']),
  reference('Holiey Souler', 'character', 'Vindietu’s young assistant, expert pickpocket, and opponent of the Sky-Guard.', ['Pokpick']),
  reference('Mina Muem', 'character', 'Competent but overly yielding corporal serving Vindietu.'),
  reference('Harashat the Reddened', 'character', 'Older corporal serving Vindietu, seeking money and bloodshed.'),
  reference('Fairtree Warehouse', 'landmark', 'Logistics and economics centre for the Doulm border quarry projects.', ['The Wearhouse']),
  reference('House Fairtree', 'organization', 'Noble family entrusted by the Crown to manage the quarry warehouse logistics and economics.', ['The Fairtrees']),
  reference('Baroness Shandrie Fairtree', 'character', 'Jewellery-laden Fairtree noble overseeing the warehouse.'),
  reference('Baron Downoal Fairtree', 'character', 'Blind Fairtree warlock whose patron granted devilsight at the cost of his eyes.'),
  reference('Aish Fairtree', 'character', 'Spoiled child of the Fairtrees.'),
  reference('Fairtree Villa', 'landmark', 'Fairtree family home west of the quarry, sought as an intelligence target.'),
  reference('Cold Shoulders', 'faction', 'Fairtree household guard identified by steel shoulder guards.'),
  reference('Whisper', 'character', 'Owl-type Sky-Guard spymaster using disguise magic to infiltrate the Fairtree intelligence network.'),
  reference('Bracers of Featherblade', 'item', 'Whisper’s bracers, conjuring feather-shaped daggers.'),
  reference('Fring Awair', 'character', 'Information smuggler between the Fairtrees and Illoni; alive and hidden.'),
  reference('Agink Flockfiler', 'character', 'Dead intelligence officer who partnered with Stagrous Fids.'),
  reference('Stagrous Fids', 'character', 'Dead Doulmian spy tied to the Fairtree intelligence plot.', ['Stigarious Fids']),
  reference('Jamm Jhahi', 'character', 'Messenger manipulated by Whisper with multiple spells after killing Stagrous Fids.'),
  reference('Aghar Flitter', 'character', 'King’s Red courier during the escalating outpost crisis.'),
  reference('The Twins', 'faction', 'Agents called in by Thomas Creed to counterattack Whisper and create an opening to infiltrate Sund.'),

  // Sund and the crypt
  reference('Sund', 'town', 'Ruined City of Worship controlled by Talon Bloodwing and the Sky-Guard.', ['Sund, The City of Worship']),
  reference('Talon Bloodwing', 'character', 'Near-immortal eagle-type Second Generation leader of the Sky-Guard and ruler of Sund.'),
  reference('Sky-Guard', 'faction', 'Aarakocra-dominated criminal and military force controlling the Illoni–Doulm surface border and ransom captives.', ['Aaracockrid Sky-Guard', 'Arachrid Sky-Guard']),
  reference('Thri-Kreen', 'faction', 'Ground force dominated by the Sky-Guard for surface operations and captive control.'),
  reference('Sund Quarry', 'landmark', 'Sky-Guard ransom site and forced-labour quarry controlled by Vultures.', ['Quarry: Vorrek']),
  reference('Vultures', 'faction', 'Sky-Guard avian group overseeing the Sund Quarry.'),
  reference('City Jail of Sund', 'landmark', 'Repaired prison and ransom site operated by Crows.', ['City Jail']),
  reference('Crows', 'faction', 'Sky-Guard avian group operating the City Jail of Sund.'),
  reference('Fortress of Sund', 'landmark', 'Fortress above hidden chambers containing gear, a spellbook, and an access point to Hujin’s crypt.'),
  reference('Crypt of Hujin Juunat', 'landmark', 'Necrotic limestone crypt beneath Sund, containing Hujin’s failed Contingency.', ['Crypt of Hujin Juunit']),
  reference('Hujin Juunat', 'historical-figure', 'Archmage entombed beneath Sund whose crypt and Contingency are central to the arc.', ['Hujin Juunit']),
  reference("Hujin's Contingency", 'item', 'Hujin’s failed Contingency, sealed behind an inscription-driven stone door.'),
  reference('Temple of Silvin', 'landmark', 'Old temple in Sund.'),
  reference('Temple of Eldorin', 'landmark', 'Old temple in Sund.'),
  reference('Temple of Eryab', 'landmark', 'Ancient temple in Sund.'),
  reference('Temple of Vorrak', 'landmark', 'Ancient temple in Sund.', ['Temple of Varrak']),

  // Other settlements explicitly listed for later chapters
  reference('Rivercleave', 'town', 'Sharlaian city listed for later campaign locations.'),
  reference('Dos', 'town', 'Sharlaian city listed for later campaign locations.'),
  reference('Ferenk', 'town', 'Sharlaian city listed for later campaign locations.'),
  reference('Grand Ferenk', 'town', 'Sharlaian city listed for later campaign locations.'),
  reference('Quencil', 'town', 'Sharlaian city listed for later campaign locations.'),
  reference('Vielle', 'town', 'Zsweon city listed for later campaign locations.'),
  reference('Midway', 'town', 'Zsweon city listed for later campaign locations.'),
  reference('TickTown', 'town', 'Levenvey city listed for later campaign locations.'),
  reference('Westway', 'road', 'Road in Levenvey.'),
  reference('Woodcrack Inn', 'landmark', 'Travel inn listed for later campaign use.')
];

export function remainingTalesOnUnwrittenTomesReferences(existing: readonly WorldbuildingEntry[]): CuratedReference[] {
  const known = new Set(existing.flatMap((entry) => [entry.name, ...entry.aliases]).map((name) => normalizeWorldbuildingName(name).toLocaleLowerCase()));
  return talesOnUnwrittenTomesReferences.filter((candidate) => ![candidate.name, ...(candidate.aliases ?? [])]
    .map((name) => normalizeWorldbuildingName(name).toLocaleLowerCase())
    .some((name) => known.has(name)));
}
